# Generated by Django 4.2.6 on 2024-09-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='str_account_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='str_secret_key',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
