# Generated by Django 4.2.6 on 2024-09-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_customer_str_account_id_customer_str_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='str_region',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='str_account_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
