# Generated by Django 4.2.6 on 2024-09-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_customer_str_region_alter_customer_str_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='str_account_id',
            new_name='str_aws_account_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='str_region',
            new_name='str_aws_region',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='str_secret_key',
            new_name='str_aws_secret_key',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='str_cod_aws_account',
        ),
    ]
