# Generated by Django 3.2.5 on 2024-06-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_alter_columns_str_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columns',
            name='str_datatype',
            field=models.CharField(choices=[('string', 'String'), ('int', 'Integer'), ('bigint', 'BigInt'), ('double', 'Float'), ('timestamp', 'Date'), ('timestamp', 'Datetime')], max_length=60),
        ),
    ]
