# Generated by Django 4.2.6 on 2024-08-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_raciactivity_str_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrun',
            old_name='dth_last_updated',
            new_name='dth_ended_at',
        ),
        migrations.RemoveField(
            model_name='jobrun',
            name='int_total_rows',
        ),
        migrations.RemoveField(
            model_name='jobrun',
            name='int_total_size',
        ),
        migrations.AddField(
            model_name='jobrun',
            name='str_context_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='str_jr_ingestion_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='str_unique_execution_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='str_event_bucket_trigger',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='str_event_key_trigger',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='str_status',
            field=models.CharField(blank=True, choices=[('RUNNING', 'RUNNING'), ('FAILED', 'FAILED'), ('SUCCEDED', 'SUCCEDED')], max_length=20, null=True),
        ),
    ]
