# Generated by Django 4.2.6 on 2024-08-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_rename_dth_last_updated_jobrun_dth_ended_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrun',
            old_name='str_context_id',
            new_name='str_jr_context_id',
        ),
    ]
