# Generated by Django 4.2.6 on 2024-08-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrun',
            name='str_status',
            field=models.CharField(blank=True, choices=[('RUNNING', 'RUNNING'), ('FAILED', 'FAILED'), ('SUCCEEDED', 'SUCCEEDED')], max_length=20, null=True),
        ),
    ]
