# Generated by Django 4.2.6 on 2024-08-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_alter_jobrun_str_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrun',
            name='dth_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='str_status',
            field=models.CharField(choices=[('RUNNING', 'RUNNING'), ('FAILED', 'FAILED'), ('SUCCEEDED', 'SUCCEEDED')], default='RUNNING', max_length=20),
        ),
    ]
