# Generated by Django 4.2.6 on 2024-09-11 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_customuser_password'),
        ('process', '0009_alter_jobrun_dth_ended_at_alter_jobrun_str_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('dth_start_at', models.DateTimeField()),
                ('str_title', models.CharField(max_length=80)),
                ('str_desc', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.customer')),
                ('raci_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.raciactivity')),
            ],
        ),
    ]
