# Generated by Django 4.2.6 on 2024-09-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_jobrun_step_jobrun_str_athena_execution_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrun',
            name='dth_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
