# Generated by Django 4.2.6 on 2024-09-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0012_alter_jobrun_dth_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrun',
            name='dth_start_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='str_status',
            field=models.CharField(choices=[('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('FAILED', 'FAILED'), ('SUCCEEDED', 'SUCCEEDED'), ('CANCELLED', 'CANCELLED')], default='RUNNING', max_length=20),
        ),
    ]
