# Generated by Django 4.2.6 on 2024-10-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_alter_jobrun_dth_start_at_alter_jobrun_str_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrun',
            name='str_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
