# Generated by Django 4.2.6 on 2024-10-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0014_jobrun_str_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrun',
            name='str_desc',
        ),
    ]
