# Generated by Django 4.2.6 on 2024-10-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0015_remove_jobrun_str_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='str_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
