name: Start Stop RDS Instance

on:
  schedule:
    - cron: '0 3 * * *'  # Desligar a RDS às 00:00 BRT (03:00 UTC)
    - cron: '0 10 * * *' # Ligar a RDS às 07:00 BRT (10:00 UTC)
  workflow_dispatch:  # Permite disparar a job manualmente

jobs:
  stop-rds:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 3 * * *'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Altere para a região onde está sua instância RDS

    - name: Stop RDS instance
      run: |
        aws rds stop-db-instance --db-instance-identifier my-db-instance-id
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  start-rds:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 10 * * *'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Altere para a região onde está sua instância RDS

    - name: Start RDS instance
      run: |
        aws rds start-db-instance --db-instance-identifier my-db-instance-id
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
