name: Start RDS Instance and ECS Instance

on:
  # schedule:
  #   - cron: '0 15 * * 1-5'  # Este cron job será executado todos os dias às 03:00 UTC
  workflow_dispatch:  # Permite disparar a job manualmente

jobs:
  stop-rds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Altere para a região onde está sua instância RDS

    - name: Start RDS Instance
      run: |
        aws rds start-db-instance --db-instance-identifier datalake
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Start ECS Cluster
      run: |
        aws ecs update-service --cluster plank --service plank-news --desired-count 1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
